import { escapeLiteralControlCharsInJsonStrings } from "./tool-call-parser.js";

/**
 * Repairs malformed JSON payloads generated by specific LLM providers (e.g., Grok/xAI).
 * Target fixes:
 * 1. Missing closing braces (common in streaming termination).
 * 2. Unescaped internal quotes inside JSON strings.
 * 3. Normalization of reasoning fields embedded inside tool call bodies.
 * 
 * Returns the repaired JSON string, or null if it cannot be repaired.
 */
export function repairMalformedJsonPayload(payload: string): string | null {
  let repaired = payload.trim();

  // 1. Remove embedded thought/reasoning tags if they incorrectly leaked into the JSON block
  repaired = repaired.replace(/<thought>[\s\S]*?<\/thought>/g, "");
  repaired = repaired.replace(/<think>[\s\S]*?<\/think>/g, "");

  // 2. Specialized Grok repairs (Machine 7)
  // Fix 1: Trailing commas in objects/arrays
  repaired = repaired.replace(/,([\]}])/g, "$1");

  // Fix 2: Unbalanced braces/brackets (common in truncated streams)
  const openBracesCount = (repaired.match(/\{/g) || []).length;
  const closeBracesCount = (repaired.match(/\}/g) || []).length;
  if (openBracesCount > closeBracesCount) {
    repaired += "}".repeat(openBracesCount - closeBracesCount);
  }

  const openBracketsCount = (repaired.match(/\[/g) || []).length;
  const closeBracketsCount = (repaired.match(/\]/g) || []).length;
  if (openBracketsCount > closeBracketsCount) {
    repaired += "]".repeat(openBracketsCount - closeBracketsCount);
  }

  // Unterminated string repair
  const quoteCount = (repaired.match(/"/g) || []).length;
  if (quoteCount % 2 !== 0) {
    repaired += '"';
  }

  // 3. Verify if it parses now
  try {
    JSON.parse(repaired);
    return repaired; // Success
  } catch (err) {
    // 4. Try fixing unescaped quotes inside string literals
    try {
      repaired = escapeLiteralControlCharsInJsonStrings(repaired);
      // Basic unescaped quote fix (lookaround heuristic)
      repaired = repaired.replace(/(?<=:\s*"(?:[^"\\]|\\.)*)(?<!\\)"(?=(?:[^"\\]|\\.)*")/g, '\\"');
      JSON.parse(repaired);
      return repaired;
    } catch (err2) {
      return null;
    }
  }
}
